### ISSUE TITLE
Change position and responsiveness of the footer

### ISSUE THREAD

**Issue by kaxada** [badging/eventBadging#56]
As of this commit -> 0c8420dd0469f292f17aafc1317f65709c4c96fb, the footer is in the wrong position. Look at this [deployed version](https://badging-website.netlify.app/) of that commit. 

In this issue, you are required to;
* Change the position of the footer to the bottom of the page
* Change the Mobile responsiveness of the footer to correspond with the design in this [Figma file](https://www.figma.com/file/7tiuJbwakgDu15mOjzKTDK/Badging-Website?node-id=1626%3A4627&t=njpDMYfbokNwYaHG-0)
* Make sure the CHAOSS logo in the footer is completely visible

**Comment by davidfcopozo** [comment]
Hello, I'd love to contribute to this project, can this issue be assigned to me?

**Comment by kaxada** [comment]
Yes @davidfcopozo. I'll assign it to you. Please make sure you create a draft PR and push every commit as soon as you finish for easier review

**Comment by davidfcopozo** [comment]
Hello @kaxada I have a question. Are we taking a mobile-first approach?

Since I'm working on the responsiveness of the footer it'd be good.

Another thing is that the white CHAOSS logo does not correspond to the one in the Figma file, the whole logo.

This is the one in the project's assets:
![image](https://user-images.githubusercontent.com/46207472/208264141-68c15d7d-cc8b-4981-a3fe-c8571eb98749.png)

and this is the one in the Figma file:
![image](https://user-images.githubusercontent.com/46207472/208264185-61eaea62-a8f8-444b-8c33-8cc6be2666e6.png)
